on: push
name: cibuild on push
jobs:
  build:
    name: "GitHub Pages Tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 3.1
          - 3.3
    steps:
    - uses: actions/checkout@master
    - name: script/cibuild-docker
      run: script/cibuild-docker
      env:
        RUBY_VERSION: ${{ matrix.ruby }}
        JEKYLL_GITHUB_TOKEN: ${{ github.token }}
