# Workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll site to Pages

on:
  # Runs schedule
  schedule:
    - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  gh_pages:
    name: Build & Deploy Github Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.gh_pages.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build & Deploy
        id: gh_pages
        uses: dunkmann00/jekyll-v4-gh-pages@v1
        with:
          source: site
